### ISSUE TITLE
Hacksu Alumni Information

### ISSUE THREAD

**Issue by cseitz** [hacksu/hacksu-2021#13]
(sorry for previous email, pinged you all in the wrong spot oof)

## Hacksu Alumni Page
Hey guys! Right now we're working on a new Alumni page for the hacksu website.

We want to make sure everyone is on this page.

### This issue is being created in an effort to contact all of you and put your info on the website.

WIP Alumni Page:
<img src="https://cseitz.dev/i/ogvhpa6" height="300">

### Your Graduation
What semester and year did you graduate? (example: SPRING 2023)

### Your Description
What was your job/role/contribution in Hacksu?
- Examples:
  - __Specific roles/jobs__: Developer, Sponsorship, Marketing, President, etc.
  - __Contributions__: Bult Kent Hack Enough's Backend, Started Game Night, etc.
  - __Fun titles__: Color-scheme Master, Workaholic, etc.

You can use up to 3 of any of these (due to available space). **At minimum 1 job/role.**

They don't have to be on this list, the list is just to help you understand of what I'm looking for.

### Your Picture
We automatically use your GitHub profile photo, which will auto-update forever.

I recommend updating your GitHub profile picture to a nice photo of you or of something you want to represent you.

**If you don't want to do this**, I can also specify an image manually; but it won't auto-update.

If you do not want to update your GitHub profile and want a specific picture to represent you, please send it to me and I'll put it in as an override.

I can also specify remote images, so if you use twitter a bunch I can probably just have it use your twitter profile image and keep the auto-update functionality. If your image is not a remote resource, you will need to contact current Hacksu leadership if you ever want it to be updated to something else.

## How to Contact Me
Please comment on this issue with your information, it'll make a nice record for future leaders about who did what in the past.

If you need to contact me directly outside of GitHub, I can send my email and/or discord upon request.

If you do not want to be on the alumni page, just say so on a comment here and I'll remove you.

If we are unable to contact you after trying a few methods and waiting a bit, we will assume you do not want to be included on the website and will remove you.

## Examples
<p float="left">
<img src="https://cseitz.dev/i/7dnxetf" height="350">
<img src="https://cseitz.dev/i/yxea8jh" height="350">
<img src="https://cseitz.dev/i/80hracy" height="350">
<img src="https://cseitz.dev/i/n1ntlzv" height="350">
<img src="https://cseitz.dev/i/0oshjr9" height="350">
</p>

@PJ-Leyden
@ktakattack
@bhollan5
@BrunerSam
@bwarring24
@camdenfullmer
@chancrystal
@danielgur
@davidsteinberg
@EFrankhouse
@dkelsey3
@gabdullah
@IAPark
@ibedard16
@JakeTobin
@mackenziekinzel
@mzrimsek
@NickCrawford
@nletdara
@nlinscott
@pdilyard
@sammyanthag
@TylerYanke
@UnitedstatesofAsia
@valazeinali
@wesdelp

**Comment by cseitz** [comment]
AWAITING APPROVAL BEFORE SENDING OUT TO EVERYONE

**Comment by cseitz** [comment]
@PJ-Leyden
@ktakattack
@bhollan5
@BrunerSam
@bwarring24
@camdenfullmer
@chancrystal
@danielgur
@davidsteinberg
@EFrankhouse
@dkelsey3
@gabdullah
@IAPark
@ibedard16
@JakeTobin
@mackenziekinzel
@mzrimsek
@NickCrawford
@nletdara
@nlinscott
@pdilyard
@sammyanthag
@TylerYanke
@UnitedstatesofAsia
@valazeinali
@wesdelp

**Comment by cseitz** [comment]
@Elizabeth1998

**Comment by camdenfullmer** [comment]
👋🏻 

Spring 2014
Founded Hacksu along with David and Daniel.

**Comment by ktakattack** [comment]
Graduated Fall 2020
Outreach & Marketing 2018-2020

**Comment by JakeTobin** [comment]
Graduated Fall 2015

**Comment by pdilyard** [comment]
Graduated Fall 2015
Leader

along w/ @robinbonatesta who for some reason left this GH org, but told me she wouldn't mind being on the alumni page. You can put her down as Leader, Graduated Spring 2016

**Comment by mackenziekinzel** [comment]
Hi! Graduated Fall 2018, Leader - Marketing and Food

I know we always talked about adding a history page to the site (lol @bhollan5 @NickCrawford) so I'm glad to see it happening 😄

**Comment by cseitz** [comment]
<img src="https://cseitz.dev/i/j77n57y">

Does this look OK? Any adjustments you guys would like?

@camdenfullmer @danielgur @davidsteinberg

**Comment by cseitz** [comment]
<img src="https://cseitz.dev/i/patriox">

Does this look OK? Any adjustments you would like?

@ktakattack

**Comment by camdenfullmer** [comment]
> ![](https://camo.githubusercontent.com/11cfbf859fed839affa1523b4228219c6185cf2c4f611f2d23004f6f75a84f21/68747470733a2f2f63736569747a2e6465762f692f6a37376e353779)
> 
> Does this look OK? Any adjustments you guys would like?
> 
> @camdenfullmer @danielgur @davidsteinberg

Looks great to me! I'm not positive that David graduated in Spring 2014 though.

**Comment by cseitz** [comment]
<img src="https://cseitz.dev/i/rcy0wrl">

Does this look OK? Any adjustments you would like?

@JakeTobin

**Comment by cseitz** [comment]
> > ![](https://camo.githubusercontent.com/11cfbf859fed839affa1523b4228219c6185cf2c4f611f2d23004f6f75a84f21/68747470733a2f2f63736569747a2e6465762f692f6a37376e353779)
> > Does this look OK? Any adjustments you guys would like?
> > @camdenfullmer @danielgur @davidsteinberg
> 
> Looks great to me! I'm not positive that David graduated in Spring 2014 though.

Ok. I'll put them back to 1990 (the placeholder I'm using to know if I've fully updated a person or not).

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110153582-3f52b380-7db1-11eb-9e2e-808c7a6f1856.png)
![image](https://user-images.githubusercontent.com/54898870/110153602-4679c180-7db1-11eb-8027-2d0ef0407a0b.png)

How's this look? Any adjustments you guys would like?

@pdilyard @robinbonatesta

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110153817-88a30300-7db1-11eb-9012-1397364e146a.png)

How does this look? Any adjustments you would like?

@mackenziekinzel

**Comment by cseitz** [comment]
![fTVVUeBd3i](https://user-images.githubusercontent.com/54898870/110154619-75446780-7db2-11eb-9a47-40178c20727d.gif)

Starting to look really good!

**Comment by cseitz** [comment]
You guys can view the current in-dev site at https://hacksu.club/

(I own hacksu.club, I bought it because it was cheap. We still __officially__ use hacksu.com as our domain)

If you have time, let me know your thoughts. I think it looks super snazzy, but I'm the one who built it so I'm pretty biased.

**Comment by mackenziekinzel** [comment]
Looks great to me - thanks!

**Comment by IAPark** [comment]
I'm unsure if I should say May 2017 or 2018. I graduated from computer science in 2017, but sort of stuck around doing Biology until 2018. 

Developer, leader is probably the right set of role for me

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110162221-7084b100-7dbc-11eb-903b-a680d568c563.png)

How's this look? Any adjustments you would like?

@IAPark

**Comment by PJ-Leyden** [comment]
That looks sick!

For mine, would you mind terribly adding Leader and then under that, "The
Comic Relief" :)
I think that'd be pretty funny

Best,
Paul "P.J." Leyden

Software Engineer
E: pjleyden1@gmail.com

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110169596-e857d900-7dc6-11eb-9278-b92ad00571f6.png)

@PJ-Leyden

**Comment by PJ-Leyden** [comment]
HAHAHA! PERFECT!
Best,
Paul "P.J." Leyden

Software Engineer
E: pjleyden1@gmail.com

**Comment by nlinscott** [comment]
Graduated: Spring 2016
Role: Android & Web Developer
Contributions: Lesson Facilitator

--
It would be cool to also include their degree or area of study since not everyone was computer science. Lots of business majors, economics, math, bio, grad students, etc. I'd be interested to see how diverse the group is in that respect.

**Comment by mzrimsek** [comment]
Graduated: Spring 2017
Role: Developer

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110214586-43470a00-7e73-11eb-8139-fb8d2658b247.png)

How's this look? Any adjustments you like?

@nlinscott 

An in regards to area of study, I can look into that. I'd prefer to have another section on the card for that because I feel like it doesn't really fit into the list of items. Kind of like "Graduated in ..." is separate from the list.

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110214639-886b3c00-7e73-11eb-9998-cd03893421b7.png)

How's this look? Any adjustments you would like?

@mzrimsek

**Comment by mzrimsek** [comment]
Looks perfect

**Comment by bhollan5** [comment]
!! I love this.
I graduated spring 2019.
Lesson planner/leader is fine for me.
nickname for me: "CSS Respecter"
And if we can do a quote, put "Understand your magic boxes" :)

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110274223-530e3d80-7f9c-11eb-9cc4-b5cb3bd03f0d.png)

How's this look?

@bhollan5

**Comment by gabdullah** [comment]
Graduated: Spring 2019 with a CS degree
Role: Leader

**Comment by cseitz** [comment]
![image](https://user-images.githubusercontent.com/54898870/110386529-64a02580-802e-11eb-91e2-500d2d02c61a.png)

How's this? Do you have a specific photo you would like for me to put in for you?

@gabdullah
